name: CI Workflow

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build steps here
      - name: Build
        run: echo "Building the project..."

      # Example step to simulate success or failure
      - name: Simulate Test
        run: |
          # Simulate a failure for demonstration purposes
          exit 1  # Change this to `exit 0` for a successful run

      - name: Notify Teams
        uses: ./.github/actions/notify_teams
        with:
          overall-status: ${{ job.status }}
          run-url: ${{ github.run_url }}
          action-name: "Build and Test"
          workflow-status: "CI Workflow"
          user1-name: ${{ vars.TEAMS_USER1_NAME }}
          user1-id: ${{ vars.TEAMS_USER1_ID }}
          user2-name: ${{ vars.TEAMS_USER2_NAME }}
          user2-id: ${{ vars.TEAMS_USER2_ID }}
          user3-name: ${{ vars.TEAMS_USER3_NAME }}
          user3-id: ${{ vars.TEAMS_USER3_ID }}
          teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}  # Pass secret as input
