name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Project
        run: echo "Building the project..."

      - name: Notify Teams
        uses: ./path/to/your/action.yml
        with:
          overall-status: ${{ job.status }}
          run-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          action-name: 'Build Job'
          workflow-status: 'Running'
          user1-name: ${{ vars.TEAMS_USER1_NAME }}
          user1-id: ${{ vars.TEAMS_USER1_ID }}
          user2-name: ${{ vars.TEAMS_USER2_NAME }}
          user2-id: ${{ vars.TEAMS_USER2_ID }}
          user3-name: ${{ vars.TEAMS_USER3_NAME }}
          user3-id: ${{ vars.TEAMS_USER3_ID }}
